// leave off @2x/@3x
const images = {
  logo: require('../Images/logo.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),

  monday: require('../Images/monday.png'),
  tuesday: require('../Images/tuesday.png'),
  wednesday: require('../Images/wednesday.png'),
  thursday: require('../Images/thursday.png'),
  friday: require('../Images/friday.png'),
  saturday: require('../Images/saturday.png'),
  sunday: require('../Images/sunday.png'),
 
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  bin:require('../Images/bin.png'),

  user: require('../Images/user.png'),
  userPlaceholder: require('../Images/userPlaceholder.png'),
  lock: require('../Images/lock.png'),
  inbox: require('../Images/inbox.png'),
  circleArrow: require('../Images/circle-arrow.png'),
  circleArrowLeft: require('../Images/circle-arrow-left.png'),  
  circleArrowRight: require('../Images/circle-arrow-right.png'),  
  BGTwentyFourHrs: require('../Images/BGTwentyFourHrs.png'),
  BgDay: require('../Images/BgDay.jpeg'),
  BgLateEvening: require('../Images/BgLateEvening.png'),
  BgEarlyMorning: require('../Images/BgEarlyMorning.png'),
  BgEvening: require('../Images/BgEvening.png'),
  hamburger: require('../Images/hamburger.png'),
  aside: require('../Images/aside.png'),
  aside1: require('../Images/aside1.png'),
  navIcon1: require('../Images/nav-icon1.png'),
  navIcon2: require('../Images/nav-icon2.png'),
  navIcon3: require('../Images/nav-icon3.png'),
  navIcon4: require('../Images/nav-icon4.png'),
  navIcon5: require('../Images/nav-icon5.png'),
  navIcon6: require('../Images/nav-icon6.png'),
  navIcon7: require('../Images/nav-icon7.png'),
  navIcon8: require('../Images/nav-icon8.png'),  
  navIcon9: require('../Images/nav-icon9.png'),  
  navIcon10: require('../Images/nav-icon10.png'),  
  navIcon11: require('../Images/nav-icon11.png'),  
  navIcon12: require('../Images/nav-icon12.png'),
  upload: require('../Images/upload.png'),  
  clock: require('../Images/clock.png'),  
  clock_school: require('../Images/clock_school.png'),  
  clockPurple: require('../Images/clock-purple.png'),
  clockPurpleLight: require('../Images/clock-purple-01.png'),
  clockFaceDigit: require('../Images/clock-face-digit.png'),
  clockFaceDigit24HRS: require('../Images/clock-face-digit_24hrs.png'),
  am:require('../Images/AM.png'),
  pm:require('../Images/PM.png'),
  pm_am:require('../Images/PM_AM.png'),
  am_pm:require('../Images/AM_PM.png'),
  clockTimer: require('../Images/clock-timer.png'),
  icon1: require('../Images/icon1.png'),
  icon2: require('../Images/icon2.png'),
  icon3: require('../Images/icon3.png'),
  icon4: require('../Images/icon4.png'),
  next: require('../Images/next.png'),
  prev: require('../Images/prev.png'),
  alarmClock: require('../Images/alarm-clock.png'),
  bell: require('../Images/bell.png'),
  school: require('../Images/school.png'),
  schoolBus: require('../Images/school-bus.png'),
  schoolBag: require('../Images/school-bag.png'),
  blueBackground: require('../Images/blue-bg.png'),
  downarrow: require('../Images/downarrow.png'),
  editTask: require('../Images/editTask.png'),
  tick: require('../Images/tick.png'),
  reward: require('../Images/reward.png'),
  cyanBackground:require('../Images/bgCyan.png'),
  arrowDown: require('../Images/arrow_down.png'),

  reward_star: require('../Images/reward-star.png'),
  reward_bomb: require('../Images/reward-bomb.png'),
  reward_diamond: require('../Images/reward-diamond.png'),
  reward_duck: require('../Images/reward-duck.png'),
  reward_flower: require('../Images/reward-flower.png'),
  reward_leaf: require('../Images/reward-leaf.png'),
  reward_settings: require('../Images/reward-settings.png'),

  
  rewardClaim: require('../Images/reward-claim.png'),
  everyday: require('../Images/everyday.png'),
  special: require('../Images/special.png'),
  close: require('../Images/close.png'),
  taskReward: require('../Images/task-reward.png'),
  circleArrowBack: require('../Images/circle-arrow-back.png'),
  shape:require('../Images/shape.png'),
  shapeRight:require('../Images/shape-right.png'),
  facebook:require('../Images/facebook.png'),
  twitter:require('../Images/twitter.png'),
  email:require('../Images/email.png'),
  unchecked: require('../Images/unchecked.png'),
  checked: require('../Images/checked.png'),
  add: require('../Images/Add.png'),
  delete: require('../Images/bin.png'),
  edit: require('../Images/Edit.png'),
  success_animation: require('../Images/sucess_animation.gif'),
  cross: require('../Images/cross.png')
}

export default images
